# Generated by Django 5.0.6 on 2024-05-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('content', models.TextField(max_length=150)),
                ('iconClass', models.TextField(max_length=100)),
            ],
        ),
    ]
