# Generated by Django 5.0.6 on 2024-05-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_services_servicemodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Quoters/')),
                ('h5tag', models.CharField(max_length=50)),
                ('paragraph1', models.TextField(max_length=200)),
                ('regards', models.TextField(max_length=80)),
            ],
        ),
    ]
