# Generated by Django 5.0.6 on 2024-05-09 18:36

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_quotemodels_paragraph1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotemodels',
            name='paragraph1',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='quotemodels',
            name='regards',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
