# Generated by Django 5.0.6 on 2024-05-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_quotemodels_paragraph1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iconClass', models.CharField(max_length=100)),
                ('numbers', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
