# Generated by Django 5.0.6 on 2024-05-10 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_breifservicemodels'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodels',
            name='briefModel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.breifservicemodels'),
            preserve_default=False,
        ),
    ]
