# Generated by Django 4.2.13 on 2024-08-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_contactmodels_workingweekend'),
    ]

    operations = [
        migrations.CreateModel(
            name='mentorsModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='mentors/')),
                ('name', models.CharField(max_length=80)),
                ('expertise', models.CharField(max_length=150)),
                ('website', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='AboutCards',
        ),
        migrations.DeleteModel(
            name='QuoteModels',
        ),
        migrations.DeleteModel(
            name='WorkModels',
        ),
    ]
