# Generated by Django 5.1 on 2024-08-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_mentorsmodels_delete_aboutcards_delete_quotemodels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorsmodels',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
