# Generated by Django 5.1 on 2024-08-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_mentorsmodels_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorsmodels',
            name='order',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
