# Generated by Django 5.0.6 on 2024-05-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_quotemodels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotemodels',
            name='paragraph1',
            field=models.TextField(max_length=250),
        ),
    ]
