# Generated by Django 5.0.6 on 2024-05-10 04:35

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_aboutcards'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreifServiceModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('image', models.ImageField(blank=True, null=True, upload_to='Services/')),
                ('topic', models.CharField(max_length=100)),
            ],
        ),
    ]
