# Generated by Django 5.0.6 on 2024-05-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_servicemodels_briefmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='works/')),
                ('prjName', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=250)),
            ],
        ),
    ]
