# Generated by Django 5.0.6 on 2024-05-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_workmodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonial/')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=200)),
                ('position', models.CharField(max_length=100)),
            ],
        ),
    ]
