# Generated by Django 5.0.6 on 2024-05-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_testimonialmodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('workingHrs', models.CharField(max_length=150)),
            ],
        ),
    ]
