# Generated by Django 5.0.6 on 2024-05-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contactmodels'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodels',
            name='workingweekend',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
