# Generated by Django 5.1 on 2024-09-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_scrollcontenmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrollcontenmodel',
            name='text4',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrollcontenmodel',
            name='text5',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
