# Generated by Django 5.1 on 2024-09-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_scrollcontenmodel_text4_scrollcontenmodel_text5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrollcontenmodel',
            name='text1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scrollcontenmodel',
            name='text2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scrollcontenmodel',
            name='text3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scrollcontenmodel',
            name='text4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scrollcontenmodel',
            name='text5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
